### PR TITLE
Redux in react components

### PR DESCRIPTION
**Pull request by blase147**
In this PR;
   I added redux to react components

### CODE REVIEW

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi @blase147, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Ouch-gifs-38715704-365-199

You have submitted a project that's not using the [updated readme template](https://github.com/microverseinc/readme-template). Kindly modify your readme file using the newly recommended template. Check the announcement channel on slack for more information about the template.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by AmaduKamara — CHANGES_REQUESTED** [review]
# Status: Required Changes ♻️♻️♻️ 

Hi @blase147,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

## Required Changes ♻️
_Check the comments under the review._
✅ You used Gitflow correctly
✅ LIinter checks passed 
✅ Configured redux 👍 
✅ README is great 👍 

Good job so far on setting up Redux in your project but at the moment, you've not wired up redux to work with the app components so adding or removing a book is possible.

- [ ] In your create new book component, kindly have states for the book title, and author by using the useState hook that is passed to the input fields value properties and when the values are changed, the onChange prop changes the state values for these input fields and then wire up a dispatch to push the data to the redux store. Kindly work on that. Adding books to the store is not functional at the moment. 
- [ ] It's required you have a function responsible for submitting form data to your redux store from the create book component. Kindly work on that so a book is saved to the redux store 👍 
- [ ] When displaying the book title and author in your Book component which receives props, kindly wire the redux functionality to dispatch a function for deleting the book from the store. Currently, when the remove button is clicked, nothing happens because you're having static data rendered to the screen. Please work on that 👍 
- [ ] The Categories components' check status button should dispatch a function when the button is clicked and then you should use the useSelector hook to fetch the state for the categories that display "Under Construction" to the screen as required. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by blase147** [comment]
Please how do I fix the linters errors I am getting on GITHUB? On my VScode everything seems fine

**Comment by AmaduKamara** [comment]
In your project, look at the bottom bar or your VSCode, you will see a link CRLF, click it and you'll be given the option to change it. When the option appears, click on the LF one. Do that of all the pages/files you have errors on in GitHub and then push your changes.

image

**Comment by blase147** [comment]
I did that but found the reverse of the error
image

**Comment by blase147** [comment]
I keep getting these errors only on Github
image

**Comment by blase147** [comment]
@AmaduKamara I keep getting these errors only on Github. On my VSCode everything works pretty fine. 
image

**Comment by rloterh** [comment]
@blase147 
I think you should first try auto-fixing the Eslint errors using the command `npx eslint . --fix`

Cheers! 😃

**Comment by blase147** [comment]
@rloterh It's done now. Awaiting approval. Thanks

**Review by rloterh — COMMENTED** [review]
Hi Chukwuma, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that your app is not running correctly. Kindly change `Components` to `components` so that your app can run correctly, and then request another review 😃 

**Compile error:**
image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by blase147** [comment]
@rloterh The components directory is in uppercase which makes the path of the app correct. Are you suggesting that I change the directory filename to lowercase(i.e from Components to components)?
image

**Review by julie-ify — APPROVED** [review]
Hi @blase147,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rloterh** [comment]
Hi @blase147 
As you can see in my attached screenshot, `components` was in lowercase. And, good job for making recommended changes

Cheers! 😃

**Pull request merged**
